def runner
node {
    checkout scm
    runner = load('ci/pipelines/microservicePipeline.groovy')
}
runner.runMicroservicePipeline([
    serviceName: 'eureka',
    servicePath: 'backEnd/Eureka',
    imageName: 'eureka',
    deploymentName: 'eureka',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])

