def runner
node {
    checkout scm
    runner = load('ci/pipelines/microservicePipeline.groovy')
}
runner.runMicroservicePipeline([
    serviceName: 'frontend',
    servicePath: 'frontend/smart-freelance-app',
    imageName: 'frontend',
    deploymentName: 'frontend',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])

