sonar.projectKey=smart-freelance-frontend
sonar.projectName=Smart Freelance Frontend
sonar.sources=src/app
sonar.sourceEncoding=UTF-8
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
