def runner
node {
    checkout scm
    runner = load('ci/pipelines/microservicePipeline.groovy')
}
runner.runMicroservicePipeline([
    serviceName: 'meeting',
    servicePath: 'backEnd/Microservices/Meeting',
    imageName: 'meeting',
    deploymentName: 'meeting',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])

