def runner = load('ci/pipelines/microservicePipeline.groovy')
runner.runMicroservicePipeline([
    serviceName: 'review',
    servicePath: 'backEnd/Microservices/review',
    imageName: 'review',
    deploymentName: 'review',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])
