def runner
node {
    checkout scm
    runner = load('ci/pipelines/microservicePipeline.groovy')
}
runner.runMicroservicePipeline([
    serviceName: 'contract',
    servicePath: 'backEnd/Microservices/Contract',
    imageName: 'contract',
    deploymentName: 'contract',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])

