def runner
node {
    checkout scm
    runner = load('ci/pipelines/microservicePipeline.groovy')
}
runner.runMicroservicePipeline([
    serviceName: 'notification',
    servicePath: 'backEnd/Microservices/Notification',
    imageName: 'notification',
    deploymentName: 'notification',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])

