def runner
node {
    checkout scm
    runner = load('ci/pipelines/microservicePipeline.groovy')
}
runner.runMicroservicePipeline([
    serviceName: 'api-gateway',
    servicePath: 'backEnd/apiGateway',
    imageName: 'api-gateway',
    deploymentName: 'api-gateway',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])

