def runner = load('ci/pipelines/microservicePipeline.groovy')
runner.runMicroservicePipeline([
    serviceName: 'subcontracting',
    servicePath: 'backEnd/Microservices/Subcontracting',
    imageName: 'subcontracting',
    deploymentName: '',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])
