node {
    checkout scm
    def runner = load('ci/pipelines/microservicePipeline.groovy')
    runner.runMicroservicePipeline([
    serviceName: 'project',
    servicePath: 'backEnd/Microservices/Project',
    imageName: 'project',
    deploymentName: 'project',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])
}
