from pathlib import Path
import nbformat as nbf


def write_nb(path: Path, cells):
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    path.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, path)


def classification_notebook(path: Path):
    cells = [
        nbf.v4.new_markdown_cell(
            "# Project Success Classification\n"
            "This notebook predicts whether a project succeeds (`success_flag`) and compares multiple algorithms.\n\n"
            "Workflow: **compréhension des données** → **nettoyage explicite (dans ce notebook)** → "
            "**pré-traitement sklearn (imputation / encodage / scaling dans un pipeline ajusté sur le train)** → "
            "entraînement → métriques → graphiques."
        ),
        nbf.v4.new_code_cell(
            "import warnings\n"
            "warnings.filterwarnings('ignore')\n"
            "from pathlib import Path\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "import seaborn as sns\n"
            "from sklearn.model_selection import train_test_split\n"
            "from sklearn.compose import ColumnTransformer\n"
            "from sklearn.pipeline import Pipeline\n"
            "from sklearn.impute import SimpleImputer\n"
            "from sklearn.preprocessing import OneHotEncoder, StandardScaler\n"
            "from sklearn.linear_model import LogisticRegression\n"
            "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n"
            "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, ConfusionMatrixDisplay\n"
            "\n"
            "ROOT = Path.cwd().resolve().parents[0] if Path.cwd().name == 'notebooks' else Path.cwd().resolve()\n"
            "if (ROOT / 'ml-workspace').exists():\n"
            "    ROOT = ROOT / 'ml-workspace'\n"
            "DATA_PATH = ROOT / 'data/raw/modeling_dataset.csv'\n"
            "RESULTS_PLOTS = ROOT / 'results/plots'\n"
            "RESULTS_METRICS = ROOT / 'results/metrics'\n"
            "RESULTS_PLOTS.mkdir(parents=True, exist_ok=True)\n"
            "RESULTS_METRICS.mkdir(parents=True, exist_ok=True)\n"
            "SEED = 42"
        ),
        nbf.v4.new_code_cell(
            "df = pd.read_csv(DATA_PATH)\n"
            "display(df.head())\n"
            "print(df.info())\n"
            "print(df['success_flag'].value_counts(normalize=True).rename('class_ratio'))"
        ),
        nbf.v4.new_markdown_cell(
            "## Exploration et diagnostic\n"
            "Contrôle des valeurs manquantes et d'un résumé statistique avant nettoyage."
        ),
        nbf.v4.new_code_cell(
            "null_report = df.isna().mean().sort_values(ascending=False)\n"
            "display(null_report[null_report > 0])\n"
            "display(df.describe(include='all').T.head(20))"
        ),
        nbf.v4.new_markdown_cell(
            "## Nettoyage des données (étapes explicites)\n"
            "1. Suppression des doublons complets.\n"
            "2. Suppression des lignes sans cible.\n"
            "3. Imputation **dans le notebook** des numériques (médiane) et des catégorielles (mode) "
            "pour documenter le traitement ; le `Pipeline` garde les mêmes étapes ajustées **uniquement sur le train** "
            "pour éviter la fuite d'information au moment du `fit`."
        ),
        nbf.v4.new_code_cell(
            "target = 'success_flag'\n"
            "clean_df = df.copy()\n"
            "n0 = len(clean_df)\n"
            "clean_df = clean_df.drop_duplicates().reset_index(drop=True)\n"
            "print(f'Doublons supprimés: {n0 - len(clean_df)} ligne(s)')\n"
            "clean_df = clean_df.dropna(subset=[target]).copy()\n"
            "print('Lignes après suppression des NaN sur la cible:', len(clean_df))\n"
            "\n"
            "null_before = clean_df.isna().sum()\n"
            "num_cols_all = clean_df.select_dtypes(include=[np.number]).columns.tolist()\n"
            "for c in num_cols_all:\n"
            "    if clean_df[c].isna().any():\n"
            "        med = clean_df[c].median()\n"
            "        nmiss = clean_df[c].isna().sum()\n"
            "        clean_df[c] = clean_df[c].fillna(med)\n"
            "        print(f'Imputation médiane {c}: {nmiss} valeur(s) -> {med:.4g}')\n"
            "cat_cols_all = clean_df.select_dtypes(exclude=[np.number]).columns.tolist()\n"
            "if target in cat_cols_all:\n"
            "    cat_cols_all.remove(target)\n"
            "for c in cat_cols_all:\n"
            "    if clean_df[c].isna().any():\n"
            "        mode = clean_df[c].mode(dropna=True)\n"
            "        fill = mode.iloc[0] if len(mode) else 'unknown'\n"
            "        nmiss = clean_df[c].isna().sum()\n"
            "        clean_df[c] = clean_df[c].fillna(fill)\n"
            "        print(f'Imputation mode {c}: {nmiss} valeur(s) -> {fill}')\n"
            "\n"
            "null_after = clean_df.isna().sum()\n"
            "display(pd.DataFrame({'avant': null_before, 'apres': null_after}).fillna(0).astype(int).T)"
        ),
        nbf.v4.new_markdown_cell(
            "## Pré-traitement (train / test + `ColumnTransformer`)\n"
            "Les transformateurs ci-dessous sont **fit** uniquement sur `X_train` via le `Pipeline` pour respecter le protocole anti-fuite."
        ),
        nbf.v4.new_code_cell(
            "drop_cols = ['project_id','title','status','client_satisfaction_score', target]\n"
            "features = [c for c in clean_df.columns if c not in drop_cols]\n"
            "X, y = clean_df[features], clean_df[target]\n"
            "\n"
            "num_cols = X.select_dtypes(include=[np.number]).columns.tolist()\n"
            "cat_cols = X.select_dtypes(exclude=[np.number]).columns.tolist()\n"
            "\n"
            "preprocessor = ColumnTransformer([\n"
            "    ('num', Pipeline([\n"
            "        ('imputer', SimpleImputer(strategy='median')),\n"
            "        ('standardize', StandardScaler())\n"
            "    ]), num_cols),\n"
            "    ('cat', Pipeline([\n"
            "        ('imputer', SimpleImputer(strategy='most_frequent')),\n"
            "        ('encode', OneHotEncoder(handle_unknown='ignore'))\n"
            "    ]), cat_cols)\n"
            "])\n"
            "\n"
            "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.22, random_state=SEED, stratify=y)\n"
            "print('Train shape:', X_train.shape, 'Test shape:', X_test.shape)"
        ),
        nbf.v4.new_code_cell(
            "models = {\n"
            "    'logistic_regression': LogisticRegression(max_iter=400, random_state=SEED),\n"
            "    'random_forest_classifier': RandomForestClassifier(n_estimators=240, random_state=SEED),\n"
            "    'gradient_boosting_classifier': GradientBoostingClassifier(random_state=SEED)\n"
            "}\n"
            "\n"
            "rows = []\n"
            "roc_store = []\n"
            "for name, model in models.items():\n"
            "    pipe = Pipeline([('prep', preprocessor), ('model', model)])\n"
            "    pipe.fit(X_train, y_train)\n"
            "    y_pred = pipe.predict(X_test)\n"
            "    if hasattr(pipe.named_steps['model'], 'predict_proba'):\n"
            "        y_score = pipe.predict_proba(X_test)[:, 1]\n"
            "    else:\n"
            "        raw = pipe.decision_function(X_test)\n"
            "        y_score = (raw - raw.min()) / (raw.max() - raw.min() + 1e-9)\n"
            "\n"
            "    rows.append({\n"
            "        'algorithm': name,\n"
            "        'accuracy': accuracy_score(y_test, y_pred),\n"
            "        'precision': precision_score(y_test, y_pred, zero_division=0),\n"
            "        'recall': recall_score(y_test, y_pred, zero_division=0),\n"
            "        'f1': f1_score(y_test, y_pred, zero_division=0),\n"
            "        'roc_auc': roc_auc_score(y_test, y_score)\n"
            "    })\n"
            "\n"
            "    ConfusionMatrixDisplay.from_predictions(y_test, y_pred, cmap='Blues')\n"
            "    plt.title(f'Confusion Matrix - {name}')\n"
            "    plt.tight_layout()\n"
            "    plt.savefig(RESULTS_PLOTS / f'classification_confusion_{name}.png', dpi=160)\n"
            "    plt.show()\n"
            "\n"
            "    fpr, tpr, _ = roc_curve(y_test, y_score)\n"
            "    roc_store.append((name, fpr, tpr))\n"
            "\n"
            "metrics_df = pd.DataFrame(rows).sort_values('f1', ascending=False)\n"
            "display(metrics_df)\n"
            "metrics_df.to_csv(RESULTS_METRICS / 'classification_metrics.csv', index=False)\n"
            "metrics_df.to_json(RESULTS_METRICS / 'classification_metrics.json', orient='records', indent=2)"
        ),
        nbf.v4.new_code_cell(
            "plt.figure(figsize=(7,5))\n"
            "for name, fpr, tpr in roc_store:\n"
            "    plt.plot(fpr, tpr, label=name)\n"
            "plt.plot([0,1],[0,1],'k--')\n"
            "plt.xlabel('False Positive Rate')\n"
            "plt.ylabel('True Positive Rate')\n"
            "plt.title('ROC Curves - All Classification Algorithms')\n"
            "plt.legend()\n"
            "plt.tight_layout()\n"
            "plt.savefig(RESULTS_PLOTS / 'classification_roc_all_algorithms.png', dpi=160)\n"
            "plt.show()\n"
            "print('Best model based on F1:', metrics_df.iloc[0]['algorithm'])"
        ),
    ]
    write_nb(path, cells)


def regression_notebook(path: Path):
    cells = [
        nbf.v4.new_markdown_cell(
            "# Client Satisfaction Regression\n"
            "This notebook predicts `client_satisfaction_score` and compares multiple regression algorithms.\n\n"
            "Le **nettoyage** (doublons, cible manquante, traitement des extrêmes) est réalisé **dans ce notebook** "
            "avant le `train_test_split` ; le pipeline sklearn applique ensuite imputation / scaling sur le jeu d'entraînement uniquement."
        ),
        nbf.v4.new_code_cell(
            "import warnings\n"
            "warnings.filterwarnings('ignore')\n"
            "from pathlib import Path\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "import seaborn as sns\n"
            "from scipy import stats\n"
            "from sklearn.model_selection import train_test_split\n"
            "from sklearn.compose import ColumnTransformer\n"
            "from sklearn.pipeline import Pipeline\n"
            "from sklearn.impute import SimpleImputer\n"
            "from sklearn.preprocessing import OneHotEncoder, MinMaxScaler, StandardScaler\n"
            "from sklearn.linear_model import LinearRegression\n"
            "from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor\n"
            "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\n"
            "\n"
            "ROOT = Path.cwd().resolve().parents[0] if Path.cwd().name == 'notebooks' else Path.cwd().resolve()\n"
            "if (ROOT / 'ml-workspace').exists():\n"
            "    ROOT = ROOT / 'ml-workspace'\n"
            "DATA_PATH = ROOT / 'data/raw/modeling_dataset.csv'\n"
            "RESULTS_PLOTS = ROOT / 'results/plots'\n"
            "RESULTS_METRICS = ROOT / 'results/metrics'\n"
            "RESULTS_PLOTS.mkdir(parents=True, exist_ok=True)\n"
            "RESULTS_METRICS.mkdir(parents=True, exist_ok=True)\n"
            "SEED = 42"
        ),
        nbf.v4.new_code_cell(
            "df = pd.read_csv(DATA_PATH)\n"
            "display(df.head())\n"
            "print(df['client_satisfaction_score'].describe())\n"
            "sns.histplot(df['client_satisfaction_score'], bins=30, kde=True)\n"
            "plt.title('Target Distribution - client_satisfaction_score')\n"
            "plt.show()"
        ),
        nbf.v4.new_markdown_cell(
            "## Nettoyage des données (étapes explicites)\n"
            "1. Suppression des doublons et des lignes sans score de satisfaction.\n"
            "2. Imputation simple des manquants sur les colonnes numériques (médiane) et catégorielles (mode) pour traçabilité.\n"
            "3. **Réduction des extrêmes** sur `deadline_overrun_days`, `avg_task_delay_days`, `budget_usd` par plage IQR "
            "(winsorisation / clipping) afin de limiter l'influence des queues de distribution, comme dans le guide de pré-traitement."
        ),
        nbf.v4.new_code_cell(
            "target = 'client_satisfaction_score'\n"
            "clean_df = df.copy()\n"
            "n0 = len(clean_df)\n"
            "clean_df = clean_df.drop_duplicates().reset_index(drop=True)\n"
            "print(f'Doublons supprimés: {n0 - len(clean_df)} ligne(s)')\n"
            "clean_df = clean_df.dropna(subset=[target]).copy()\n"
            "print('Lignes après suppression des NaN sur la cible:', len(clean_df))\n"
            "\n"
            "null_before = clean_df.isna().sum()\n"
            "num_cols_all = clean_df.select_dtypes(include=[np.number]).columns.tolist()\n"
            "for c in num_cols_all:\n"
            "    if clean_df[c].isna().any():\n"
            "        med = clean_df[c].median()\n"
            "        nmiss = clean_df[c].isna().sum()\n"
            "        clean_df[c] = clean_df[c].fillna(med)\n"
            "        print(f'Imputation médiane {c}: {nmiss} valeur(s)')\n"
            "cat_cols_all = clean_df.select_dtypes(exclude=[np.number]).columns.tolist()\n"
            "if target in cat_cols_all:\n"
            "    cat_cols_all.remove(target)\n"
            "for c in cat_cols_all:\n"
            "    if clean_df[c].isna().any():\n"
            "        mode = clean_df[c].mode(dropna=True)\n"
            "        fill = mode.iloc[0] if len(mode) else 'unknown'\n"
            "        clean_df[c] = clean_df[c].fillna(fill)\n"
            "        print(f'Imputation mode {c}')\n"
            "\n"
            "clip_cols = ['deadline_overrun_days', 'avg_task_delay_days', 'budget_usd']\n"
            "bounds = {}\n"
            "for col in clip_cols:\n"
            "    q1, q3 = clean_df[col].quantile([0.25, 0.75])\n"
            "    iqr = q3 - q1\n"
            "    lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n"
            "    bounds[col] = (lower, upper)\n"
            "    before = clean_df[col].describe()[['min', 'max']]\n"
            "    clean_df[col] = clean_df[col].clip(lower, upper)\n"
            "    after = clean_df[col].describe()[['min', 'max']]\n"
            "    print(f'{col}: bornes IQR [{lower:.3g}, {upper:.3g}] — min/max avant {before.to_dict()} apres {after.to_dict()}')\n"
            "\n"
            "fig, axes = plt.subplots(1, len(clip_cols), figsize=(4 * len(clip_cols), 4))\n"
            "if len(clip_cols) == 1:\n"
            "    axes = [axes]\n"
            "for ax, col in zip(axes, clip_cols):\n"
            "    sns.boxplot(y=clean_df[col], ax=ax, color='#93c5fd')\n"
            "    ax.set_title(f'Après clipping — {col}')\n"
            "plt.tight_layout()\n"
            "plt.show()\n"
            "\n"
            "null_after = clean_df.isna().sum()\n"
            "display(pd.DataFrame({'avant': null_before, 'apres': null_after}).fillna(0).astype(int).T)"
        ),
        nbf.v4.new_markdown_cell(
            "## Pré-traitement (pipeline + découpage train / test)\n"
            "Normalisation `MinMaxScaler` + `StandardScaler` sur le bloc numérique et encodage one-hot sur le bloc catégoriel, "
            "comme dans le script `run_all_models.py`."
        ),
        nbf.v4.new_code_cell(
            "drop_cols = ['project_id','title','status','success_flag', target]\n"
            "features = [c for c in clean_df.columns if c not in drop_cols]\n"
            "X, y = clean_df[features], clean_df[target]\n"
            "\n"
            "num_cols = X.select_dtypes(include=[np.number]).columns.tolist()\n"
            "cat_cols = X.select_dtypes(exclude=[np.number]).columns.tolist()\n"
            "\n"
            "preprocessor = ColumnTransformer([\n"
            "    ('num', Pipeline([\n"
            "        ('imputer', SimpleImputer(strategy='median')),\n"
            "        ('normalize', MinMaxScaler()),\n"
            "        ('standardize', StandardScaler())\n"
            "    ]), num_cols),\n"
            "    ('cat', Pipeline([\n"
            "        ('imputer', SimpleImputer(strategy='most_frequent')),\n"
            "        ('encode', OneHotEncoder(handle_unknown='ignore'))\n"
            "    ]), cat_cols)\n"
            "])\n"
            "\n"
            "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.22, random_state=SEED)"
        ),
        nbf.v4.new_code_cell(
            "models = {\n"
            "    'linear_regression': LinearRegression(),\n"
            "    'random_forest_regressor': RandomForestRegressor(n_estimators=260, random_state=SEED),\n"
            "    'gradient_boosting_regressor': GradientBoostingRegressor(random_state=SEED)\n"
            "}\n"
            "rows = []\n"
            "for name, model in models.items():\n"
            "    pipe = Pipeline([('prep', preprocessor), ('model', model)])\n"
            "    pipe.fit(X_train, y_train)\n"
            "    pred = pipe.predict(X_test)\n"
            "    residuals = y_test - pred\n"
            "    rows.append({\n"
            "        'algorithm': name,\n"
            "        'mae': mean_absolute_error(y_test, pred),\n"
            "        'rmse': np.sqrt(mean_squared_error(y_test, pred)),\n"
            "        'r2': r2_score(y_test, pred)\n"
            "    })\n"
            "\n"
            "    plt.figure(figsize=(6,5))\n"
            "    plt.scatter(y_test, pred, alpha=0.55)\n"
            "    lo, hi = min(y_test.min(), pred.min()), max(y_test.max(), pred.max())\n"
            "    plt.plot([lo,hi],[lo,hi],'r--')\n"
            "    plt.xlabel('Actual')\n"
            "    plt.ylabel('Predicted')\n"
            "    plt.title(f'Predicted vs Actual - {name}')\n"
            "    plt.tight_layout()\n"
            "    plt.savefig(RESULTS_PLOTS / f'regression_pred_vs_actual_{name}.png', dpi=160)\n"
            "    plt.show()\n"
            "\n"
            "    fig, axes = plt.subplots(1,2,figsize=(10,4))\n"
            "    sns.histplot(residuals, kde=True, ax=axes[0])\n"
            "    axes[0].set_title(f'Residual Distribution - {name}')\n"
            "    stats.probplot(residuals, dist='norm', plot=axes[1])\n"
            "    axes[1].set_title(f'QQ Plot - {name}')\n"
            "    plt.tight_layout()\n"
            "    plt.savefig(RESULTS_PLOTS / f'regression_residuals_{name}.png', dpi=160)\n"
            "    plt.show()\n"
            "\n"
            "metrics_df = pd.DataFrame(rows).sort_values('r2', ascending=False)\n"
            "display(metrics_df)\n"
            "metrics_df.to_csv(RESULTS_METRICS / 'regression_metrics.csv', index=False)\n"
            "metrics_df.to_json(RESULTS_METRICS / 'regression_metrics.json', orient='records', indent=2)\n"
            "print('Best model based on R2:', metrics_df.iloc[0]['algorithm'])"
        ),
    ]
    write_nb(path, cells)


def clustering_notebook(path: Path):
    cells = [
        nbf.v4.new_markdown_cell(
            "# Client Segmentation Clustering\n"
            "This notebook clusters clients by behavior and compares clustering algorithms.\n\n"
            "Le **nettoyage** (cohérence des clés, valeurs manquantes post-fusion, valeurs infinies) est détaillé **dans ce notebook** "
            "avant le `ColumnTransformer` et le clustering."
        ),
        nbf.v4.new_code_cell(
            "import warnings\n"
            "warnings.filterwarnings('ignore')\n"
            "from pathlib import Path\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "import seaborn as sns\n"
            "from sklearn.compose import ColumnTransformer\n"
            "from sklearn.pipeline import Pipeline\n"
            "from sklearn.impute import SimpleImputer\n"
            "from sklearn.preprocessing import OneHotEncoder, StandardScaler\n"
            "from sklearn.decomposition import PCA\n"
            "from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN\n"
            "from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score\n"
            "\n"
            "ROOT = Path.cwd().resolve().parents[0] if Path.cwd().name == 'notebooks' else Path.cwd().resolve()\n"
            "if (ROOT / 'ml-workspace').exists():\n"
            "    ROOT = ROOT / 'ml-workspace'\n"
            "CLIENTS_PATH = ROOT / 'data/raw/clients.csv'\n"
            "PROJECTS_PATH = ROOT / 'data/raw/projects.csv'\n"
            "RESULTS_PLOTS = ROOT / 'results/plots'\n"
            "RESULTS_METRICS = ROOT / 'results/metrics'\n"
            "RESULTS_PLOTS.mkdir(parents=True, exist_ok=True)\n"
            "RESULTS_METRICS.mkdir(parents=True, exist_ok=True)\n"
            "SEED = 42"
        ),
        nbf.v4.new_code_cell(
            "clients = pd.read_csv(CLIENTS_PATH)\n"
            "projects = pd.read_csv(PROJECTS_PATH)\n"
            "print('clients:', clients.shape, '| projects:', projects.shape)\n"
            "display(clients.head(3))\n"
            "display(projects.head(3))"
        ),
        nbf.v4.new_markdown_cell(
            "## Construction du jeu client + agrégats projets\n"
            "Agrégation par `client_id` puis jointure ; les clients sans projet conservent des NaN sur les colonnes agrégées."
        ),
        nbf.v4.new_code_cell(
            "agg = projects.groupby('client_id', as_index=False).agg(\n"
            "    mean_completion_ratio=('completion_ratio', 'mean'),\n"
            "    mean_delay_days=('avg_task_delay_days', 'mean'),\n"
            "    project_success_rate=('success_flag', 'mean'),\n"
            "    mean_budget_usd=('budget_usd', 'mean'),\n"
            "    avg_complexity=('complexity_score', 'mean'),\n"
            "    total_projects=('project_id', 'count')\n"
            ")\n"
            "merged = clients.merge(agg, on='client_id', how='left')\n"
            "print('Lignes après merge:', len(merged))\n"
            "dup_ids = merged['client_id'].duplicated().sum()\n"
            "print('client_id dupliqués:', int(dup_ids))\n"
            "display(merged.isna().mean().sort_values(ascending=False).head(15))"
        ),
        nbf.v4.new_markdown_cell(
            "## Nettoyage des données (étapes explicites)\n"
            "1. Remplacement des `inf` / `-inf` issus d'agrégations éventuelles par NaN.\n"
            "2. Imputation des colonnes numériques post-merge par la **médiane** (robuste).\n"
            "3. Imputation des colonnes catégorielles par le **mode** (ou libellé `'unknown'`).\n"
            "4. Le pipeline ci-dessous refait une imputation fit sur les données pour alignement avec `run_all_models.py`."
        ),
        nbf.v4.new_code_cell(
            "df = merged.copy()\n"
            "df = df.replace([np.inf, -np.inf], np.nan)\n"
            "null_before = df.isna().sum()\n"
            "num_cols_all = df.select_dtypes(include=[np.number]).columns.tolist()\n"
            "for c in num_cols_all:\n"
            "    if df[c].isna().any():\n"
            "        med = df[c].median()\n"
            "        df[c] = df[c].fillna(med)\n"
            "cat_cols_all = df.select_dtypes(exclude=[np.number]).columns.tolist()\n"
            "if 'client_id' in cat_cols_all:\n"
            "    cat_cols_all.remove('client_id')\n"
            "for c in cat_cols_all:\n"
            "    if df[c].isna().any():\n"
            "        mode = df[c].mode(dropna=True)\n"
            "        fill = mode.iloc[0] if len(mode) else 'unknown'\n"
            "        df[c] = df[c].fillna(fill)\n"
            "null_after = df.isna().sum()\n"
            "print('Total NaN restants:', int(null_after.sum()))\n"
            "display(pd.DataFrame({'avant': null_before, 'apres': null_after}).fillna(0).astype(int).T)\n"
            "display(df.head())"
        ),
        nbf.v4.new_markdown_cell(
            "## Pré-traitement (encodage + mise à l'échelle) et PCA pour la visualisation\n"
            "`fit_transform` sur tout `X` ici pour le clustering exploratoire ; en production on isolerait un jeu d'apprentissage."
        ),
        nbf.v4.new_code_cell(
            "X = df.drop(columns=['client_id'])\n"
            "num_cols = X.select_dtypes(include=[np.number]).columns.tolist()\n"
            "cat_cols = X.select_dtypes(exclude=[np.number]).columns.tolist()\n"
            "\n"
            "preprocessor = ColumnTransformer([\n"
            "    ('num', Pipeline([\n"
            "        ('imputer', SimpleImputer(strategy='median')),\n"
            "        ('standardize', StandardScaler())\n"
            "    ]), num_cols),\n"
            "    ('cat', Pipeline([\n"
            "        ('imputer', SimpleImputer(strategy='most_frequent')),\n"
            "        ('encode', OneHotEncoder(handle_unknown='ignore'))\n"
            "    ]), cat_cols)\n"
            "])\n"
            "Xp = preprocessor.fit_transform(X)\n"
            "Xp_dense = Xp.toarray() if hasattr(Xp, 'toarray') else Xp\n"
            "pca = PCA(n_components=2, random_state=SEED)\n"
            "X2 = pca.fit_transform(Xp_dense)"
        ),
        nbf.v4.new_code_cell(
            "algorithms = {\n"
            "    'kmeans': KMeans(n_clusters=4, random_state=SEED, n_init=10),\n"
            "    'agglomerative': AgglomerativeClustering(n_clusters=4),\n"
            "    'dbscan': DBSCAN(eps=1.25, min_samples=7)\n"
            "}\n"
            "rows = []\n"
            "for name, algo in algorithms.items():\n"
            "    labels = algo.fit_predict(Xp_dense)\n"
            "    valid = labels != -1\n"
            "    unique = np.unique(labels[valid]) if valid.any() else np.array([])\n"
            "    if len(unique) > 1 and valid.sum() > len(unique):\n"
            "        sil = silhouette_score(Xp_dense[valid], labels[valid])\n"
            "        ch = calinski_harabasz_score(Xp_dense[valid], labels[valid])\n"
            "        db = davies_bouldin_score(Xp_dense[valid], labels[valid])\n"
            "    else:\n"
            "        sil, ch, db = np.nan, np.nan, np.nan\n"
            "\n"
            "    rows.append({\n"
            "        'algorithm': name,\n"
            "        'num_clusters': len(np.unique(labels[labels != -1])),\n"
            "        'noise_ratio': float((labels == -1).mean()),\n"
            "        'silhouette': sil,\n"
            "        'calinski_harabasz': ch,\n"
            "        'davies_bouldin': db\n"
            "    })\n"
            "\n"
            "    plt.figure(figsize=(7,5))\n"
            "    sns.scatterplot(x=X2[:,0], y=X2[:,1], hue=labels, palette='tab10', s=42, legend=False)\n"
            "    plt.title(f'Cluster Projection - {name}')\n"
            "    plt.xlabel('PCA 1')\n"
            "    plt.ylabel('PCA 2')\n"
            "    plt.tight_layout()\n"
            "    plt.savefig(RESULTS_PLOTS / f'clustering_projection_{name}.png', dpi=160)\n"
            "    plt.show()\n"
            "\n"
            "metrics_df = pd.DataFrame(rows).sort_values('silhouette', ascending=False, na_position='last')\n"
            "display(metrics_df)\n"
            "metrics_df.to_csv(RESULTS_METRICS / 'clustering_metrics.csv', index=False)\n"
            "metrics_df.to_json(RESULTS_METRICS / 'clustering_metrics.json', orient='records', indent=2)"
        ),
        nbf.v4.new_code_cell(
            "ks = range(2, 9)\n"
            "inertias, silhouettes = [], []\n"
            "for k in ks:\n"
            "    km = KMeans(n_clusters=k, random_state=SEED, n_init=10)\n"
            "    labels = km.fit_predict(Xp_dense)\n"
            "    inertias.append(km.inertia_)\n"
            "    silhouettes.append(silhouette_score(Xp_dense, labels))\n"
            "\n"
            "fig, axes = plt.subplots(1,2,figsize=(11,4))\n"
            "axes[0].plot(list(ks), inertias, marker='o')\n"
            "axes[0].set_title('KMeans Elbow Curve')\n"
            "axes[0].set_xlabel('k')\n"
            "axes[0].set_ylabel('Inertia')\n"
            "axes[1].plot(list(ks), silhouettes, marker='o')\n"
            "axes[1].set_title('KMeans Silhouette Trend')\n"
            "axes[1].set_xlabel('k')\n"
            "axes[1].set_ylabel('Silhouette')\n"
            "plt.tight_layout()\n"
            "plt.savefig(RESULTS_PLOTS / 'clustering_kmeans_curves.png', dpi=160)\n"
            "plt.show()\n"
            "print('Best clustering algorithm (highest silhouette):', metrics_df.iloc[0]['algorithm'])"
        ),
    ]
    write_nb(path, cells)


def main():
    root = Path(__file__).resolve().parents[1]
    nb_dir = root / "notebooks"
    classification_notebook(nb_dir / "01_project_success_classification.ipynb")
    regression_notebook(nb_dir / "02_client_satisfaction_regression.ipynb")
    clustering_notebook(nb_dir / "03_client_segmentation_clustering.ipynb")
    print("Notebooks created.")


if __name__ == "__main__":
    main()
