def runner = load('ci/pipelines/microservicePipeline.groovy')
runner.runMicroservicePipeline([
    serviceName: 'config-server',
    servicePath: 'backEnd/ConfigServer',
    imageName: 'config-server',
    deploymentName: 'config-server',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])
