def runner = load('ci/pipelines/microservicePipeline.groovy')
runner.runMicroservicePipeline([
    serviceName: 'ticket-service',
    servicePath: 'backEnd/Microservices/ticket-service',
    imageName: 'ticket-service',
    deploymentName: '',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])
