def runner
node {
    checkout scm
    runner = load('ci/pipelines/microservicePipeline.groovy')
}
runner.runMicroservicePipeline([
    serviceName: 'keycloak-auth',
    servicePath: 'backEnd/KeyCloak',
    imageName: 'keycloak-auth',
    deploymentName: 'keycloak-auth',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])

