node {
    checkout scm
    def runner = load('ci/pipelines/microservicePipeline.groovy')
    runner.runMicroservicePipeline([
    serviceName: 'keycloak-auth',
    servicePath: 'backEnd/KeyCloak',
    imageName: 'keycloak-auth',
    deploymentName: 'keycloak-auth',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])
}
