def runner = load('ci/pipelines/microservicePipeline.groovy')
runner.runMicroservicePipeline([
    serviceName: 'freelancia-job',
    servicePath: 'backEnd/Microservices/FreelanciaJob',
    imageName: 'freelancia-job',
    deploymentName: 'freelancia-job',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])
